### ISSUE TITLE
instruments displaced in the cockpit

### ISSUE THREAD

**Issue by lomar-fgfs** [FGMEMBERS/727-230#3]
in the 727-203ADV, there are some instruments that aren't placed correctly in the panel
screenshot:
https://farm6.staticflickr.com/5743/20516580794_e15ac5147a_b.jpg

**Comment by FGDATA** [comment]
Hi!
I referenced this issue in IAHM-COLs fork, where development is currently tracking all other issues.

**Comment by JWocky** [comment]
I really wonder how you got this view, I didn't even see that.

**Comment by FGDATA** [comment]
This issue is being treated on the development repository
